# Site settings
title: Code Notes
subtitle: [ Jingruei Blog]
keywords: iewihc
description: 為學習用的私人程式筆記，參考許多網址/書籍以及整合自己的理解，如有侵權凡請告知。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iewihc.github.io/" # 你的域名
page_no_title: "0 blog" # 文章无标题时默认显示内容
beian: # "备案号"
author: iewihc
email: iewihc@outlook.com

# Build settings
permalink: /:year/:month/:day/:title/
exclude: ["README.md", "changelog.md", "server", "tools", "Pipfile"]
plugins:
  - jekyll-paginate
  - jemoji


# always get github's error email saying redcarpet is not supported,
# so change it to kramdown.
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM


# Pageinate settings
paginate: 8 # 分頁大小
paginate_path: "page/:num/"

# Search settings
google_search: true

# Menu settings
menu:
  - page: 首頁
    directory: .
    icon: icon-home
  - page: 歸檔
    directory: archives/
    icon: icon-archive
  - page: 標籤
    directory: tags/
    icon: icon-tags





# Google Analytics
ga_track_id: 'UA-130856615-1'            # Format: UA-xxxxxx-xx
ga_domain: auto            # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto


# Code hub settings
codehub: # 代码仓库
  - title: Github
    url: https://github.com/oukohou


valine:
  enable: true
  app_id:  K1rbn2Oo0YMM04VuzdLS7Nzz-gzGzoHsz
  app_key: AAsHbwVm8ofKFJ6ghGqqrXSU
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  visitor: true
  avatar: retro
  placeholder: say something~~\n - 昵称 为你所要显示的评论的ID；\n - 邮箱 只有后台可见，仅供讨论过程中是否需要交流邮件而设置，请放心填写;\n - 网址 为你的评论的昵称的超链接。\n当然，以上都可以不写，评论依然会显示……
  guest_info: nick,mail,link
  pageSize: 10

theme: jekyll-theme-minimal
